server:
  port: 80
  forward-headers-strategy: native

spring:
  application:
    name: atipicoAI

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
              - https://www.googleapis.com/auth/drive.file # Escopo para criar e gerenciar apenas os arquivos do app no Drive
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: "https://accounts.google.com/o/oauth2/v2/auth?prompt=consent&access_type=offline"

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never